@startuml
left to right direction

:User:
:Customer: as c
:Cook: as ck
:Courier: as d

:User: <|-- c

rectangle "Pizza Ordering Service" {

    usecase "Create an order" as cr
    usecase "Customize a pizza" as cmz
    usecase "Replace unavailable ingredients" as rpl
    usecase "Cancel an order" as cnl
    usecase "Track delivery" as trk
    usecase "Prepare pizza" as ppr
    usecase "Deliver pizza" as dlv
}

c --> cr
c --> cnl
c --> trk

ck --> ppr
ck --> rpl
d --> dlv

cr ..> cmz : <<include>>
rpl ..> cmz : <<extend>>

@enduml